## Henry Rollins, Anne Lamott quotes generated using ChatGPT o3

## THESE ARE NOT REAL QUOTES! THEY ARE AI-GENERATED to sound wholesome, positive, and inspiring.
teddy_ruxpin_quotes = {
    # Original 10
    "Teddy_BrandNewTomorrow": "Every page we turn together is a brand‑new tomorrow waiting to happen.",
    "Teddy_LanternFriendsPath": "Friends are the lanterns that light even the twistiest forest path.",
    "Teddy_CuriousHeartCompass": "A curious heart is the best compass—just follow where it points and you’ll never be lost.",
    "Teddy_SeedOfWonder": "When you share a story, you plant a seed of wonder that can grow in anyone’s imagination.",
    "Teddy_GentleBravery": "Bravery isn’t how loud you roar; it’s how gently you hold someone’s hand when they’re afraid.",
    "Teddy_SmallestBackpackDreams": "Sometimes the smallest backpack carries the biggest dreams.",
    "Teddy_ListeningMagic": "Listening is its own kind of magic—you can almost hear the world smile back.",
    "Teddy_CloudsMoveOn": "If a cloud slides over your sunshine, remember: clouds move on, and so will the gloomy feeling.",
    "Teddy_AdventureTellMeMore": "Adventure begins the moment you say, ‘Tell me more.’",
    "Teddy_KindWordsCampfire": "Kind words are tiny sparks; together they make the coziest campfire of all.",
    "Teddy_DreamsFearlessExplorer": "Dreams love a good map, but they adore a fearless explorer even more.",
    "Teddy_GratitudeGlowStar": "The quiet glow of gratitude can outshine the brightest star.",
    "Teddy_MistakeSteppingStone": "A mistake is just a stepping‑stone dressed in a funny costume.",
    "Teddy_SharingLaughterFireflies": "Sharing laughter is like passing around a jar of fireflies—everyone gets a little light.",
    "Teddy_PatienceHammock": "Patience is a hammock for the heart; rest in it while your hopes catch up.",
    "Teddy_WaterGardenSmellFlowers": "When you water someone else’s garden, your hands come home smelling like flowers.",
    "Teddy_ShyAcornOak": "Even the shyest acorn can become a mighty oak with a little encouragement.",
    "Teddy_QuestionsKeys": "Questions are keys; each one you ask unlocks a hidden room of understanding.",
    "Teddy_RainyDaysPuddlesSing": "Rainy days are nature's way of whispering, ‘slow down and listen to the puddles sing.’",
    "Teddy_CourageQuietShoes": "Courage often wears quiet shoes; you won't hear it coming, but you’ll feel it stand tall.",
    "Teddy_GoodbyeFutureHellos": "Every goodbye is a suitcase packed with future hellos.",
    "Teddy_FriendshipMelodyDance": "Friendship is the melody that teaches two hearts to dance in the same rhythm.",
    "Teddy_WonderContagious": "Wonder is contagious—go ahead and sneeze a little of it into the world.",
    "Teddy_KindnessOpeningDoors": "Kindness doesn't keep score; it keeps opening doors.",
    "Teddy_EnjoyMoonlight": "You don’t need to reach the moon to enjoy its light.",
    "Teddy_StoriesBoatsTime": "Stories are boats that sail across the lakes of time.",
    "Teddy_HugsShortestPoems": "Hugs are the world's shortest poems.",
    "Teddy_MistMountainsAdventures": "Mist takes the mountains on adventures; you can too.",
    "Teddy_EmptyPageParty": "An empty page is really just a party waiting for words to arrive.",
    "Teddy_HopeFirefly": "When hope feels tiny, cup your hands around it like a firefly and watch it glow.",
    "Teddy_SmilesFireworks": "Smiles are silent fireworks—bursting without a bang.",
    "Teddy_TripOnDream": "If you trip on a dream, pick it up and see where it wants to go.",
    "Teddy_PromiseClearedPath": "A promise kept is a path cleared in a forest of doubts.",
    "Teddy_WindSkyLetter": "Listening to the wind is like reading a letter the sky wrote just for you.",
    "Teddy_JoyOrdinaryMoments": "Joy can hide inside ordinary moments like a treasure in plain sight.",
    "Teddy_AdventurePageTurns": "Sometimes the best adventures happen between two page turns.",
    "Teddy_SpeakGently": "Speak gently; words can plant forests or start storms.",
    "Teddy_BelieveTomorrow": "Believe in tomorrow, but give today a standing ovation.",
    "Teddy_ShadowsLight": "Even shadows prove there’s light nearby.",
    "Teddy_CuriosityRustlessKey": "Curiosity is a key that never goes rusty.",
    "Teddy_GratitudeMiraclePockets": "Practice gratitude and you'll grow pockets big enough for miracles.",
    "Teddy_ImaginationFlapWings": "Let your imagination flap its wings; your thoughts will follow like friendly birds.",
    "Teddy_BraveryWhisperTry": "Bravery is the whisper that says ‘try’ when the roar says ‘stop.’",
    "Teddy_MinutesIntoMemories": "Time spent with friends turns minutes into memories.",
    "Teddy_SouvenirsStories": "The best souvenirs are stories you can carry in your heart.",
    "Teddy_LittleStepsOften": "Little steps taken often can outwalk giant leaps taken seldom.",
    "Teddy_ForgivenessGentleBroom": "Forgiveness is the gentle broom that sweeps worries from your doorstep.",
    "Teddy_SilenceBetweenSongs": "Silence between songs makes the music shine brighter.",
    "Teddy_DreamSeedsBedtime": "Dreams are seeds; bedtime is the soil.",
    "Teddy_AdventureOpenDoor": "Adventure doesn't always need a map, just an open door and an eager heart."
}

## Henry Rollins quotes
henry_rollins_quotes = {
    "Rollins_OptimismHeavyBoots": "My optimism wears heavy boots and is loud.",
    "Rollins_ScarTissueStrength": "Scar tissue is stronger than regular tissue. Realize the strength. Move on.",
    "Rollins_LetGoPain": "It hurts to let go. Sometimes, it seems the harder you try to hold on to something or someone, the more it wants to get away.",
    "Rollins_LonelinessBeauty": "Loneliness adds beauty to life. It puts a special burn on sunsets and makes night air smell better.",
    "Rollins_InsanityGreatThings": "You need a little bit of insanity to do great things.",
    "Rollins_StrikeHardYouthFleeting": "Youth is fleeting and life is short; you might as well strike hard. Anything else is just average.",
    "Rollins_NoSpareTime": "No such thing as spare time, no such thing as free time, no such thing as downtime. All you got is lifetime. Go.",
    "Rollins_DepressionLoneliness": "I’ll never forget how the depression and loneliness felt good and bad at the same time. Still does.",
    "Rollins_StruggleStrength": "Strength is the product of struggle. You must do what others don’t to achieve what others won’t.",
    "Rollins_PerformanceAll": "Giving a good performance—giving it all—is what it’s all about. I love to perform.",
    "Rollins_LearnFromFailure": "We all learn lessons in life. Some stick, some don’t. I have always learned more from rejection and failure than from acceptance and success.",
    "Rollins_PersonalPain": "I think about the meaning of pain. Pain is personal—probably the only thing that is your own. I like mine.",
    "Rollins_LonerCrowdedRoom": "Yes, I guess you could say I am a loner, but I feel more lonely in a crowded room with boring people than I feel on my own.",
    "Rollins_LifeCrushHeart": "Life will not break your heart. It’ll crush it.",
    "Rollins_DoubtKills": "When you start to doubt yourself, the real world will eat you alive.",
    "Rollins_TruthHurts": "Sometimes, the truth hurts—and sometimes it feels real good.",
    "Rollins_LoveOrHate": "Don’t do anything by half. If you love someone, love them with all your soul. When you hate someone, hate them until it hurts.",
    "Rollins_SoulMateShutMeUp": "I want a soul mate who can sit me down, shut me up, tell me ten things I don’t already know, and make me laugh… just have something in there.",
    "Rollins_KnowledgeMileage": "Knowledge without mileage equals bullshit.",
    "Rollins_GetThingsDone": "I just get things done instead of talking about getting them done.",
    "Rollins_PersonalWriting": "I can only write about personal stuff—about my point of view.",
    "Rollins_TimeRunningOut": "Use the time wisely because it is running out, but don’t freak out about it.",
    "Rollins_HatredParanoiaAbandonment": "I don’t believe in fate or destiny. I believe in various degrees of hatred, paranoia, and abandonment.",
    "Rollins_StrengthKindness": "Muscle mass does not always equal strength. Strength is kindness and sensitivity.",
    "Rollins_NotSeriousActor": "I take it seriously when I’m on a set, but I don’t take myself seriously as an actor.",
    "Rollins_NeverLowerYourself": "You must never lower yourself to being a person you don’t like.",
    "Rollins_SomeoneYouKnew": "It is sad when someone you know becomes someone you knew.",
    "Rollins_NoPrideMoveOn": "I have no pride about anything I have done… once I am done, I move on.",
    "Rollins_HalfLifeFUp": "Half of life is f***ing up; the other half is dealing with it.",
    "Rollins_BeautifulVisionMind": "Somewhere, someone is thinking of you… making you into a vision so beautiful that it can only live in the mind.",
    "Rollins_ForgedFromVacuum": "I forged myself out of a vacuum.",
    "Rollins_WomanRespectsHerself": "I want to meet a woman who will make my jaw drop in awe… one who respects herself.",
    "Rollins_DamageWords": "I will never say the things that I want to say to you—I know the damage it would do.",
    "Rollins_RadioShowMusic": "The lowest‑stress environment is the radio show; I can let the music do the talking.",
    "Rollins_IronGreatestFriend": "The iron is my greatest friend… two hundred pounds is always two hundred pounds.",
    "Rollins_Reinvention": "One defines oneself by reinvention. Do not be like your parents. Do not be like your friends.",
    "Rollins_AlienateYourself": "All by yourself—unable to express the pain of your distress—you alienate yourself and everybody else.",
    "Rollins_LivingRuin": "You can still function as a living ruin.",
    "Rollins_CleanBloodLeanBody": "Keep your blood clean, your body lean, and your mind sharp.",
    "Rollins_WomenBeautifulFaces": "Girls aren’t beautiful; they’re pretty. Women are beautiful because their faces show what they’ve lost and gained.",
    "Rollins_OnUntilDead": "I am on until I am dead, like a light bulb.",
    "Rollins_BornBeautifulUglyAge": "It is our destiny to be born beautiful into an ugly age.",
    "Rollins_CanBeBroken": "I know that I can be broken. I am not as tough as I thought.",
    "Rollins_MakeItThroughToday": "I’ll be here tomorrow—if I can make it through today.",
    "Rollins_OutLearnOutLive": "If you hate your parents or the establishment, out‑learn them, out‑live them, know more than they do.",
    "Rollins_LemonsWhatElse": "When life hands you a lemon, say, ‘Oh yeah, I like lemons! What else ya got?’",
    "Rollins_NoDrugsPaint": "I never did drugs, really… I would’ve rather drank a litre of paint.",
    "Rollins_RoseInFist": "A rose trapped inside a fist.",
    "Rollins_BurnedOutSelf": "I’m so burned out, the only person I can stand is myself.",
    "Rollins_LifeForgetsMe": "Life forgets me, but will not let me forget—holds me down and tells me that I’m free."
}

## Anne Lamott quotes
anne_lamott_quotes = {
    "Lamott_HopeBeginsInDark": "Hope begins in the dark, the stubborn hope that if you just show up and try to do the right thing, the dawn will come. You wait and watch and work: you don’t give up.",
    "Lamott_UnplugForMinutes": "Almost everything will work again if you unplug it for a few minutes, including you.",
    "Lamott_LoseSomeoneBrokenHeart": "You will lose someone you can’t live without, and your heart will be badly broken, and the bad news is that you never completely get over the loss of your beloved. But this is also the good news.",
    "Lamott_RatPoisonForgiveness": "Not forgiving is like drinking rat poison and then waiting for the rat to die.",
    "Lamott_PerfectionismOppressor": "Perfectionism is the voice of the oppressor, the enemy of the people. It will keep you cramped and insane your whole life.",
    "Lamott_LaughterCarbonatedHoliness": "Laughter is carbonated holiness.",
    "Lamott_GraceDifferentUniverse": "Grace means you’re in a different universe from where you had been stuck, when you had absolutely no way to get there on your own.",
    "Lamott_BirdByBird": "Bird by bird, buddy. Just take it bird by bird.",
    "Lamott_TerribleFirstEfforts": "Almost all good writing begins with terrible first efforts. You need to start somewhere.",
    "Lamott_MysteryOfGrace": "I do not understand the mystery of grace — only that it meets us where we are and does not leave us where it found us.",
    "Lamott_HopeFloatsOpens": "When hope is not pinned wriggling onto a shiny image or expectation, it sometimes floats forth and opens.",
    "Lamott_ExpectationsResentments": "Expectations are resentments waiting to happen.",
    "Lamott_JoyBestMakeup": "Joy is the best makeup.",
    "Lamott_FaithVsCertainty": "The opposite of faith is not doubt, but certainty. Certainty is missing the point entirely.",
    "Lamott_FollowRulesDontAsshole": "Rule 1: When all else fails, follow instructions. And Rule 2: Don’t be an asshole.",
    "Lamott_RestLaughterSpiritual": "Rest and laughter are the most spiritual and subversive acts of all. Laugh, rest, slow down.",
    "Lamott_OwnYourStories": "You own everything that happened to you. Tell your stories. If people wanted you to write warmly about them, they should’ve behaved better.",
    "Lamott_TeenagersAdoredByGod": "Teenagers who do not go to church are adored by God, but they don't get to meet some of the people who love God back.",
    "Lamott_GraceBatsLast": "Grace bats last.",
    "Lamott_LighthousesStandShining": "Lighthouses don’t go running all over an island looking for boats to save; they just stand there shining.",
    "Lamott_PointWithTruth": "You don't always have to chop with the sword of truth. You can point with it too.",
    "Lamott_MindNeighborhood": "My mind is a neighborhood I try not to go into alone.",
    "Lamott_RevolutionaryPatience": "Hope is a revolutionary patience.",
    "Lamott_GodInYourImage": "You can safely assume you've created God in your own image when it turns out that God hates all the same people you do.",
    "Lamott_GraceIsLight": "Grace is the light or electricity or juice or breeze that takes you from that isolated place and puts you with others.",
    "Lamott_ExtraMileBirthday": "Some people won’t go the extra mile, and then on their birthday, when no one makes a fuss, they feel neglected and bitter.",
    "Lamott_AllNewPeople": "A hundred years from now? All new people.",
    "Lamott_InsidesVsOutsides": "Never compare your insides to everyone else’s outsides.",
    "Lamott_RightOrKind": "You can either practice being right or practice being kind.",
    "Lamott_ForgivenessHitBack": "Forgiveness means it finally becomes unimportant that you hit back.",
    "Lamott_RadicalSelfCare": "Radical self‑care is quantum and radiates out into the atmosphere, like a little fresh air.",
    "Lamott_MessFailureTeachers": "My best teachers were mess, failure, death, mistakes, and the people I hated, including myself.",
    "Lamott_ThrowMoneyProblem": "If you have a problem you can solve by throwing money at it, you don’t have a very interesting problem.",
    "Lamott_HopeInHopelessness": "The reason I never give up hope is because everything is so basically hopeless.",
    "Lamott_BooksAreMedicine": "Books, for me, are medicine.",
    "Lamott_UncomfortableWeightTraining": "It's good to do uncomfortable things. It's weight training for life.",
    "Lamott_PayAttentionBeauty": "Pay attention to the beauty surrounding you.",
    "Lamott_FriendshipWithOwnHeart": "Radical self‑care is what we’ve been longing for, desperate for, our entire lives—friendship with our own hearts.",
    "Lamott_PerfectionShallow": "Perfection is shallow, unreal, and fatally uninteresting.",
    "Lamott_SweetComeback": "There is nothing as sweet as a comeback, when you are down and out, about to lose, and out of time.",
    "Lamott_SelfLoveFreedom": "I believe that discipline and self‑love are the total secrets to freedom.",
    "Lamott_HelpGiftDesperation": "The reason 'help' is such a great prayer is that God is the gift of desperation.",
    "Lamott_JustDance": "Don't look at your feet to see if you are doing it right. Just dance.",
    "Lamott_HelpPrayerAnswered": "Help is a prayer that is always answered.",
    "Lamott_StoriesSplintsSoul": "Reading and books are medicine. Stories and truth are splints for the soul.",
    "Lamott_StuckIsDeath": "If we stay where we are, where we're stuck, where we're comfortable and safe, we die there... When nothing new can get in, that's death.",
    "Lamott_GratitudeDovetailsBehavior": "Gratitude begins in our hearts and then dovetails into behavior.",
    "Lamott_FaithAndFear": "I have a lot of faith. But I am also afraid a lot, and have no real certainty about anything.",
    "Lamott_JoySweetnessAffection": "I think joy and sweetness and affection are a spiritual path.",
    "Lamott_LoveBiggerThanGrim": "Hope is not about proving anything. It's about choosing to believe this one thing, that love is bigger than any grim, bleak sh*t anyone can throw at us."
}

# Patti Smith
patti_smith_quotes = {
    "Smith_CantMistakeImprovise": "You can't make a mistake when you improvise.",
    "Smith_TransformationalInteractions": "Make your interactions with people transformational, not just transactional.",
    "Smith_FierySadnessDesire": "Never let go of that fiery sadness called desire.",
    "Smith_ShedOurSkins": "We go through life. We shed our skins. We become ourselves.",
    "Smith_SufferExtendHand": "Those who have suffered understand suffering and therefore extend their hand.",
    "Smith_JoyAliveFree": "Put down your cell phones, put everything away, and feel your blood pulsing in you … feel the joy of being alive and free.",
    "Smith_RockWithWhatYouGot": "If you don't have what you need, just rock with what you've got!",
    "Smith_PursueWhatYouWant": "What matters is to know what you want and pursue it.",
    "Smith_WriteWrongWords": "Freedom is … the right to write the wrong words.",
    "Smith_BuildGoodName": "Build a good name. Keep your name clean … eventually that name will be its own currency.",
    "Smith_AdventureDesignFate": "Life is an adventure of our own design intersected by fate and a series of lucky and unlucky accidents.",
    "Smith_GenderDrag": "As far as I'm concerned, being any gender is a drag.",
    "Smith_PeopleRedeemFools": "People have the power to redeem the work of fools.",
    "Smith_FutureAwaitsAwake": "Swift is the arrow, dark is the thorn … the future awaits, awake.",
    "Smith_LittleFlamePrevail": "If we keep our little flame alive … we will prevail.",
    "Smith_GreatestTimeNow": "I'm here right now and I want now to be the greatest time.",
    "Smith_ArtOptimistic": "Art is by nature optimistic. Art is optimistic because it is alive.",
    "Smith_LoseControlTakeControl": "Got to lose control before you take control.",
    "Smith_LeadsToEachOther": "Where does it all lead? … It leads to each other. We become ourselves.",
    "Smith_EverythingAwaitedMe": "No one expected me. Everything awaited me.",
    "Smith_DistractedByMyself": "Everything distracted me, but most of all myself.",
    "Smith_DontAbandonBook": "Please, no matter how we advance technologically, please don't abandon the book. There is nothing in our material world more beautiful than the book.",
    "Smith_ContradictionTruth": "I learned from him that often contradiction is the clearest way to truth.",
    "Smith_AwakeTheDead": "Why can't I write something that would awake the dead? That pursuit is what burns most deeply.",
    "Smith_DaydreamSolitude": "I daydream a lot … periods of small solitude that we are really losing are so important."
}

# Nick Cave
nick_cave_quotes = {
    "Cave_LimitationsDisaster": "Your limitations make you the wonderful disaster you most probably are.",
    "Cave_CannotBeIdle": "All of our days are numbered. We cannot afford to be idle.",
    "Cave_ControlWeatherMoods": "I can control the weather with my moods. I just can’t control my moods.",
    "Cave_HoldOntoFlame": "If you could hold onto that flame, great things could construct around it…",
    "Cave_WonderfulLife": "It's a wonderful life if you can find it.",
    "Cave_WriteSadSongs": "I want to write songs that are so sad, the kind of sad where you take someone's little finger and break it in three places.",
    "Cave_HeWhoSeeksFinds": "He who seeks, finds, and who knocks, will be let in.",
    "Cave_DarkerRegionsHeart": "The writer who refuses to explore the darker regions of the heart will never be able to write convincingly about the wonder, the magic and the joy of love…",
    "Cave_ArtistDutyOpenMind": "An artist's duty is rather to stay open‑minded and in a state where he can receive information and inspiration.",
    "Cave_KnowsOwnStory": "Who knows their own story? It certainly makes no sense when you’re in the middle of it.",
    "Cave_LoveContinuously": "Love is a state that I would like to exist in continuously.",
    "Cave_PursueMuse": "Most people wait for the muse to turn up. That's terribly unreliable. I have to sit down and pursue the muse by attempting to work.",
    "Cave_MusicStormingRelentless": "Music is storming, driving, relentless, devotional, slinky, subtle, heartbreakingly‑beautiful sounds…",
    "Cave_NotInterestedRelevant": "I've never been interested in being relevant.",
    "Cave_GenuineHeart": "I am not interested in anything that doesn't have a genuine heart to it. You've got to have soul in the hole.",
    "Cave_DontMeetManyLike": "You don't meet a lot of people that you really like. I don't anyway.",
    "Cave_ElementToSongwriting": "There's an element to songwriting that I can't explain, that comes from somewhere else.",
    "Cave_OptimismBrokenHeart": "Hope is optimism with a broken heart.",
    "Cave_OutOfSorrowWorlds": "Out of sorrow entire worlds have been built.",
    "Cave_StarsDie": "Stars have their moments then they die.",
    "Cave_HeavenLie": "Heaven is just a lie of mine to make it Hell on Earth.",
    "Cave_StereoGarbage": "I’m forever near a stereo saying, ‘What the fuck is this garbage?’",
    "Cave_LoveSongMadness": "The love song must be born into the realm of the irrational… love is, of course, a form of madness.",
    "Cave_ArtIsHardLabor": "The artistic process seems to be mythologized quite a lot into something far greater than it actually is. It is just hard labor.",
    "Cave_InspirationWordUsed": "'Inspiration' is a word used by people who aren't really doing anything."
}

bob_ross_quotes = {
    "Ross_HappyLittleAccidents": "We don't make mistakes, just happy little accidents.",
    "Ross_TalentPursuedInterest": "Talent is a pursued interest. Anything that you're willing to practice, you can do.",
    "Ross_TreeAsFriend": "There's nothing wrong with having a tree as a friend.",
    "Ross_TalkToTreesAnimals": "I guess I'm a little weird. I like to talk to trees and animals. That's okay though; I have more fun than most people.",
    "Ross_LetsGetCrazy": "Let's get crazy.",
    "Ross_RewardExpressPainting": "I can't think of anything more rewarding than being able to express yourself to others through painting.",
    "Ross_BelievingIsDoing": "The secret to doing anything is believing that you can do it. Anything that you believe you can do strong enough, you can do. Anything. As long as you believe.",
    "Ross_ToolsVisionMind": "All you need to paint is a few tools, a little instruction, and a vision in your mind.",
    "Ross_BeatTheDevil": "Wash the brush, just beat the devil out of it.",
    "Ross_YourWorldFreedomCanvas": "This is your world — you're the creator; find freedom on this canvas.",
    "Ross_MoveMountainsCanvas": "You have unlimited power on this canvas — you can literally move mountains.",
    "Ross_BelieveYouCan": "Believe that you can do it because you can do it.",
    "Ross_HappyCloudTrees": "Let's build a happy little cloud. Let's build some happy little trees.",
    "Ross_TalentPursuedHobby": "I started painting as a hobby when I was little. I didn't know I had any talent. I believe talent is just a pursued interest. Anybody can do what I do.",
    "Ross_SuccessBreedsSuccess": "There's nothing in the world that breeds success like success.",
    "Ross_EveryDayGoodDayPaint": "I believe every day is a good day when you paint.",
    "Ross_WindowsToSoul": "Exercising the imagination, experimenting with talents, being creative — these things, to me, are truly the windows to your soul.",
    "Ross_JoyOfPainting": "Truly, you have experienced the joy of painting!",
    "Ross_MonaLisaTwoInchBrush": "I really believe that if you practice enough you could paint the Mona Lisa with a two‑inch brush.",
    "Ross_BelieveInThemselves": "I don't intimidate anyone. Instead, I try to get people to believe in themselves.",
    "Ross_OneHourMasterpiece": "Within one hour of touching the brush to canvas for the first time, my students have a total, complete painting.",
    "Ross_DoSomethingHappyDaily": "It's so important to do something every day that will make you happy.",
    "Ross_BeautyEverywhere": "Look around. Look at what we have. Beauty is everywhere — you only have to look to see it.",
    "Ross_PrerequisiteHappiness": "The only prerequisite is that it makes you happy. If it makes you happy then it's good.",
    "Ross_GoOutOnLimb": "Go out on a limb — that's where the fruit is.",
    "Ross_OppositesInLife": "You've got to have opposites — dark and light, light and dark — in painting. It's like in life.",
    "Ross_TreesCoverSins": "Trees cover up a multitude of sins.",
    "Ross_AnyTimeYouLearnGain": "Any time you learn, you gain.",
    "Ross_EverybodyNeedsFriend": "Everybody needs a friend. Friends are the most valuable things in the world.",
    "Ross_ChangeMindHappyThings": "Isn't it fantastic that you can change your mind and create all these happy things?",
    "Ross_PaintingShouldHappy": "If painting does nothing else, it should make you happy.",
    "Ross_TalkToTreeFriend": "Just go out and talk to a tree. Make friends with it.",
    "Ross_NeedDarkForLight": "You need the dark in order to show the light.",
    "Ross_NoPressureRelax": "No pressure. Just relax and watch it happen.",
    "Ross_HappyPaintingsOnly": "We want happy paintings. If you want sad things, watch the news.",
    "Ross_AnythingThisWorld": "You can do anything you want to do. This is your world.",
    "Ross_StrongRoots": "A big strong tree needs big strong roots.",
    "Ross_WaterLazy": "Water's like me. It's lazy. It always looks for the easiest way to do things.",
    "Ross_CrookedTreeWashington": "That’s a crooked tree. We’ll send him to Washington.",
    "Ross_MakeLoveCanvas": "Make love to the canvas.",
    "Ross_HighlightNeedsShadow": "Every highlight needs its own personal shadow.",
    "Ross_NoLimitsBelieve": "There are no limits here. You start out by believing here.",
    "Ross_YellowSnowGreenSnow": "The only thing worse than yellow snow is green snow.",
    "Ross_GiveFriend": "Gotta give him a friend. Like I always say, 'Everyone needs a friend.'",
    "Ross_BigDecisionsMake": "Don't be afraid to make these big decisions. Once you start, they sort of just make themselves.",
    "Ross_LaughFeelGood": "We don't laugh because we feel good; we feel good because we laugh.",
    "Ross_TurnDislikeIntoLike": "Anything you don’t like, you can turn it into something you do like.",
    "Ross_FindFreedomCanvas": "Find freedom on this canvas.",
    "Ross_DeadTreesNormal": "In nature, dead trees are just as normal as live trees.",
    "Ross_DontSetCloudsOnFire": "We don't want to set these clouds on fire."
}

# Ryan Holiday
ryan_holiday_quotes = {
    "Holiday_ObstaclePath": "The obstacle in the path becomes the path. Never forget, within every obstacle is an opportunity to improve our condition.",
    "Holiday_PerceptionAction": "Where the head goes, the body follows. Perception precedes action. Right action follows the right perspective.",
    "Holiday_WritingNotEasy": "No one will argue that writing is an easy profession…",
    "Holiday_FocusOnMoment": "Focus on the moment, not the monsters that may or may not be up ahead.",
    "Holiday_FailureShowsWay": "Failure shows us the way – by showing us what isn't the way.",
    "Holiday_PersistenceSiege": "It's okay to be discouraged. It's not okay to quit… that’s persistence.",
    "Holiday_BuildRealLife": "Building things up in real life is better than building them up in your imagination.",
    "Holiday_EndureTragedy": "To do great things, we need to be able to endure tragedy and setbacks…",
    "Holiday_Sitzfleisch": "The Germans have a word for it: Sitzfleisch. Staying power…",
    "Holiday_IntelligentRead": "When intelligent people read, they ask themselves a simple question: What do I plan to do with this information?",
    "Holiday_WeaknessStrength": "Great individuals, like great companies, find a way to transform weakness into strength.",
    "Holiday_PerceptionStory": "There is no good or bad without us, there is only perception…",
    "Holiday_BookInvestment": "Dollar for dollar there is no better investment in the world than a book.",
    "Holiday_QuietWill": "True will is quiet humility, resilience, and flexibility…",
    "Holiday_ProblemsPerception": "Problems are rarely as bad as we think—or rather, they are precisely as bad as we think.",
    "Holiday_DecideBreakResist": "We decide what we will make of each and every situation. We decide whether we’ll break or whether we’ll resist.",
    "Holiday_DisciplinePerception": "Discipline in perception lets you clearly see the advantage and the proper course of action…",
    "Holiday_RunDigestDay": "I run 5 miles every night. It’s where I go to digest my day…",
    "Holiday_ConningConmen": "Conning the conmen is one of life’s most satisfying pleasures.",
    "Holiday_ProveOrNeeds": "Am I saying this because I want to prove how smart I am or because it needs to be said?",
    "Holiday_EntrepreneurFaith": "An entrepreneur is someone with faith in their ability to make something where there was nothing before.",
    "Holiday_PredictorAnger": "The most powerful predictor of what spreads online is anger.",
    "Holiday_TurnMisfortuneAdvantage": "Great people turn personal tragedy or misfortune to their advantage.",
    "Holiday_NoEasyNews": "You cannot have your news instantly and have it done well… There is no easy way.",
    "Holiday_ImplicitExplicit": "Before anything can be resolved, the implicit must be made explicit."
}